# Generated by Django 2.1.1 on 2018-09-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromto', models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('--', '--')], default='--', max_length=8, verbose_name='From:')),
                ('to', models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('--', '--')], default='--', max_length=8, verbose_name='To:')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(choices=[('Malaga', 'Malaga'), ('Sevilla', 'Sevilla'), ('Madrid', 'Madrid'), ('Barcelona', 'Barcelona')], max_length=100)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntario.DiasDisponibles')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Domingo',
            field=models.ManyToManyField(blank=True, related_name='domingo_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Jueves',
            field=models.ManyToManyField(blank=True, related_name='jueves_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Lunes',
            field=models.ManyToManyField(blank=True, related_name='lunes_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Martes',
            field=models.ManyToManyField(blank=True, related_name='martes_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Miercoles',
            field=models.ManyToManyField(blank=True, related_name='miercoles_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Sabado',
            field=models.ManyToManyField(blank=True, related_name='sabado_set', to='voluntario.horario'),
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='Viernes',
            field=models.ManyToManyField(blank=True, related_name='viernes_set', to='voluntario.horario'),
        ),
    ]
