# Generated by Django 2.1.1 on 2018-09-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo'), ('All', 'All')], max_length=10)),
                ('horario', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='ciudad',
            field=models.CharField(choices=[('Malaga', 'Malaga'), ('Sevilla', 'Sevilla'), ('Madrid', 'Madrid'), ('Barcelona', 'Barcelona')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluntario.Disponible'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ocupacion',
            field=models.CharField(choices=[('Medico', 'Medico'), ('Enfermero', 'Enfermero'), ('Abogado', 'Abogado'), ('Ingeniero', 'Ingeniero')], max_length=50),
        ),
    ]
