# Generated by Django 2.1.1 on 2018-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Domingo',
            field=models.ManyToManyField(blank=True, related_name='domingo_set', related_query_name='domingo_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Jueves',
            field=models.ManyToManyField(blank=True, related_name='jueves_set', related_query_name='jueves_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Lunes',
            field=models.ManyToManyField(blank=True, related_name='lunes_set', related_query_name='lunes_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Martes',
            field=models.ManyToManyField(blank=True, related_name='martes_set', related_query_name='martes_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Miercoles',
            field=models.ManyToManyField(blank=True, related_name='miercoles_set', related_query_name='miercoles_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Sabado',
            field=models.ManyToManyField(blank=True, related_name='sabado_set', related_query_name='sabado_q', to='voluntario.horario'),
        ),
        migrations.AlterField(
            model_name='diasdisponibles',
            name='Viernes',
            field=models.ManyToManyField(blank=True, related_name='viernes_set', related_query_name='viernes_q', to='voluntario.horario'),
        ),
    ]
