# Generated by Django 2.1.1 on 2018-09-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_auto_20180925_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol', to='voluntario.DiasDisponibles'),
        ),
    ]
