# Generated by Django 2.1.1 on 2018-09-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_auto_20180922_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='disponibilidad',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo'), ('All', 'All')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Disponible',
        ),
    ]
