# Generated by Django 2.1.1 on 2018-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0003_auto_20180922_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='franjaHoraria',
            field=models.CharField(blank=True, choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=20, null=True),
        ),
    ]
