# Generated by Django 2.1.1 on 2018-09-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0004_person_franjahoraria'),
        ('voluntario', '0006_auto_20180926_0109'),
    ]

    operations = [
    ]
