# Generated by Django 2.1.1 on 2018-09-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0007_merge_20180929_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='franjaHoraria',
        ),
        migrations.AlterField(
            model_name='person',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntario.DiasDisponibles'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ocupacion',
            field=models.CharField(max_length=50),
        ),
    ]
